/*--------------------------------------------------
	=============== Autorun File ===============
	*** Copyright (c) 2012-2021 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted,
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
--------------------------------------------------*/
------------------ Addon Information ------------------
local PublicAddonName = "Cry of Fear Resurgence"
local AddonName = "Cry of Fear Resurgence"
local AddonType = "SNPC"
local AutorunFile = "autorun/vj_cofr_autorun.lua"
-------------------------------------------------------
local VJExists = file.Exists("lua/autorun/vj_base_autorun.lua","GAME")
if VJExists == true then
	include('autorun/vj_controls.lua')

	-- Cry of Fear --
	local vCat = "CoF Resurgence" 
	VJ.AddCategoryInfo(vCat, {Icon = "vj_cofr/icons/cofr.png"})
	VJ.AddNPC("Slower 1","npc_vj_cofr_slower1",vCat)	
    VJ.AddNPC("Slower 3","npc_vj_cofr_slower3",vCat)
	VJ.AddNPC("Slower No","npc_vj_cofr_slowerno",vCat)
	VJ.AddNPC("Slower 10","npc_vj_cofr_slower10",vCat)
	VJ.AddNPC("Slower 10-2","npc_vj_cofr_slower102",vCat)
	VJ.AddNPC("Crawler","npc_vj_cofr_crawler",vCat)
	VJ.AddNPC("Croucher","npc_vj_cofr_croucher",vCat)
	VJ.AddNPC("Upper","npc_vj_cofr_upper",vCat)
	VJ.AddNPC("Baby","npc_vj_cofr_baby",vCat) 
	VJ.AddNPC("Children","npc_vj_cofr_children",vCat)
    VJ.AddNPC("Faster","npc_vj_cofr_faster",vCat)
	VJ.AddNPC("Faster (Male)","npc_vj_cofr_fastermale",vCat)
    VJ.AddNPC("Drowned","npc_vj_cofr_drowned",vCat)
	VJ.AddNPC("Crazyrunner","npc_vj_cofr_crazyrunner",vCat)
	VJ.AddNPC("Sewmo","npc_vj_cofr_sewmo",vCat)
	VJ.AddNPC("Citalopram","npc_vj_cofr_citalopram",vCat)
	VJ.AddNPC("Faceless","npc_vj_cofr_faceless",vCat)
    VJ.AddNPC("Faceless (Crawler)","npc_vj_cofr_faceless2",vCat)
    VJ.AddNPC("Faceless (Faced)","npc_vj_cofr_faced",vCat)
    VJ.AddNPC("Faceless (Twister)","npc_vj_cofr_twister",vCat)
    VJ.AddNPC("Faceless (Twister Valve)","npc_vj_cofr_twisterv",vCat)	
	VJ.AddNPC("Krypandenej","npc_vj_cofr_krypandenej",vCat)
    VJ.AddNPC("Suicider","npc_vj_cofr_suicider",vCat)
	VJ.AddNPC("Taller","npc_vj_cofr_taller",vCat)
    VJ.AddNPC("Psycho","npc_vj_cofr_psycho",vCat)	
	VJ.AddNPC("Stranger","npc_vj_cofr_stranger",vCat)
	VJ.AddNPC("Spitter","npc_vj_cofr_spitter",vCat)
	VJ.AddNPC("Hanger","npc_vj_cofr_hanger",vCat)
	VJ.AddNPC("Flygare","npc_vj_cofr_flygare",vCat)
	VJ.AddNPC("Dreamer","npc_vj_cofr_dreamer",vCat)
	VJ.AddNPC("Dreamer (Runner)","npc_vj_cofr_dreamerrunner",vCat)
	VJ.AddNPC("Hangman","npc_vj_cofr_hangman",vCat)
	VJ.AddNPC("Watro","npc_vj_cofr_watro",vCat)
    VJ.AddNPC("Human Flower","npc_vj_cofr_humanflower",vCat) 	
    VJ.AddNPC("The Face","npc_vj_cofr_facehead",vCat)
    VJ.AddNPC("Sawer","npc_vj_cofr_sawer",vCat)	
	VJ.AddNPC("Sawrunner","npc_vj_cofr_sawrunner",vCat)
	VJ.AddNPC("Mace","npc_vj_cofr_mace",vCat)
	VJ.AddNPC("Carcass","npc_vj_cofr_carcass",vCat)
	VJ.AddNPC("Sawcrazy","npc_vj_cofr_sawcrazy",vCat)
    VJ.AddNPC("Craig","npc_vj_cofr_craig",vCat)
	VJ.AddNPC("Book Simon","npc_vj_cofr_simonbook",vCat)	
    VJ.AddNPC("Book Simon (Manhunt)","npc_vj_cofr_simonbookm",vCat)
	VJ.AddNPC("Doctor Purnell","npc_vj_cofr_purnell",vCat)
	VJ.AddNPC("Sick Simon (Suicider)","npc_vj_cofr_simonsicksui",vCat)	
    --VJ.AddNPC("Sick Simon","npc_vj_cofr_simonsick",vCat)	

    -- CoF Random & Spawners --
	VJ.AddNPC("Random Monster","sent_vj_cofr_mon",vCat)	
    VJ.AddNPC("Random Monster Spawner","sent_vj_cofr_mon_sp",vCat)
	VJ.AddNPC("Random Monster Spawner (Single)","sent_vj_cofr_mon_sinsp",vCat)
    VJ.AddNPC("Monster Map Spawner","sent_vj_cofr_mapspawner",vCat)	
	
	-- Afraid of Monsters --
	vCat = "CoF Resurgence: AoM"
	VJ.AddCategoryInfo(vCat, {Icon = "vj_cofr/icons/cofraom.png"})	
    VJ.AddNPC("Twitcher","npc_vj_cofraom_twitcher",vCat)
	VJ.AddNPC("Twitcher (Dark Assistance)","npc_vj_cofraom_twitcherda",vCat)
    VJ.AddNPC("Handcrab","npc_vj_cofraom_handcrab",vCat)
	VJ.AddNPC("Wheelchair Twitcher","npc_vj_cofraom_wheelchair",vCat)
    VJ.AddNPC("Spitter Twitcher","npc_vj_cofraom_twitcherspit",vCat)
    VJ.AddNPC("Bleeding Spector","npc_vj_cofraom_spector",vCat)
    VJ.AddNPC("One-Eyed Dog","npc_vj_cofraom_dog",vCat)	
	VJ.AddNPC("Abomination","npc_vj_cofraom_abomination",vCat)
    VJ.AddNPC("Launcher Ghost","npc_vj_cofraom_ghost",vCat)
    VJ.AddNPC("The Addiction","npc_vj_cofraom_addiction",vCat)		

    -- AoM Random & Spawners --
	VJ.AddNPC("Random Monster","sent_vj_cofraom_mon",vCat)	
    VJ.AddNPC("Random Monster Spawner","sent_vj_cofraom_mon_sp",vCat)
	VJ.AddNPC("Random Monster Spawner (Single)","sent_vj_cofraom_mon_sinsp",vCat)
    VJ.AddNPC("Monster Map Spawner","sent_vj_cofraom_mapspawner",vCat)	

	-- Custom --
	vCat = "CoF Resurgence: Custom"
	VJ.AddCategoryInfo(vCat, {Icon = "vj_cofr/icons/cofrcustom.png"})
    VJ.AddNPC("Slower 1","npc_vj_cofrc_slower1",vCat)
	VJ.AddNPC("Slower 3","npc_vj_cofrc_slower3",vCat)
	VJ.AddNPC("Slower No","npc_vj_cofrc_slowerno",vCat)
	VJ.AddNPC("Slower 10","npc_vj_cofrc_slower10",vCat)
    VJ.AddNPC("Croucher","npc_vj_cofrc_croucher",vCat)	
    VJ.AddNPC("Crawler","npc_vj_cofrc_crawler",vCat)
	VJ.AddNPC("Crawler 2","npc_vj_cofrc_crawler2",vCat)
	VJ.AddNPC("Krypandenej","npc_vj_cofrc_krypandenej",vCat)
    VJ.AddNPC("Faceless (Claw)","npc_vj_cofrc_facelessclaw",vCat)	
    VJ.AddNPC("Faster (Clown)","npc_vj_cofrc_fasterclown",vCat)	
	VJ.AddNPC("Duorunner","npc_vj_cofrc_duorunner",vCat)	
    VJ.AddNPC("Psycho (Pumpkin)","npc_vj_cofrc_psychopumpkin",vCat)
    VJ.AddNPC("CrazyruMpel","npc_vj_cofrc_crazyrumpel",vCat)	
	
    -- Particles --
    game.AddParticles( "particles/vj_cofr_soul.pcf" )
    game.AddParticles( "particles/vj_cofr_soulsplat.pcf" )
    game.AddParticles( "particles/vj_cofr_face.pcf" )
    game.AddParticles( "particles/vj_cofr_spit.pcf" )
	game.AddParticles( "particles/vj_cofr_spitgib.pcf" )
    game.AddParticles( "particles/vj_cofr_flaresparks.pcf" )
	game.AddParticles( "particles/vj_cofr_flaretrail.pcf" )	
    PrecacheParticleSystem("face")
    PrecacheParticleSystem("aomsoul")
    PrecacheParticleSystem("aomsoulsplat")
    PrecacheParticleSystem("mommaspit")
	PrecacheParticleSystem("MommaSpitGib")
    PrecacheParticleSystem("flaresparks")
	PrecacheParticleSystem("flaretrail")	

    -- Decals --
    game.AddDecal("VJ_COFR_Blood_Red",{"vj_cofr/decals/cof_blood01","vj_cofr/decals/cof_blood02","vj_cofr/decals/cof_blood03","vj_cofr/decals/cof_blood04","vj_cofr/decals/cof_blood05","vj_cofr/decals/cof_blood06","vj_cofr/decals/cof_blood07"})
    game.AddDecal("VJ_COFR_Blood_Red_Large",{"vj_cofr/decals/cof_bigblood01","vj_cofr/decals/cof_bigblood02"})
	
	-- Precache Models --
	util.PrecacheModel("models/vj_cofr/cof/slower1.mdl")
	util.PrecacheModel("models/vj_cofr/cof/crawler.mdl")
	util.PrecacheModel("models/vj_cofr/cof/croucher.mdl")
	util.PrecacheModel("models/vj_cofr/cof/slower3.mdl")
	util.PrecacheModel("models/vj_cofr/cof/slowerno.mdl")
	util.PrecacheModel("models/vj_cofr/cof/slower10.mdl")
	util.PrecacheModel("models/vj_cofr/cof/slower102.mdl")	
	util.PrecacheModel("models/vj_cofr/cof/baby.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faster.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faster2.mdl")
	util.PrecacheModel("models/vj_cofr/cof/drowned.mdl")
	util.PrecacheModel("models/vj_cofr/cof/sewmo.mdl")
	util.PrecacheModel("models/vj_cofr/cof/crazyrunner.mdl")
	util.PrecacheModel("models/vj_cofr/cof/children.mdl")
	util.PrecacheModel("models/vj_cofr/cof/citalopram.mdl")
	util.PrecacheModel("models/vj_cofr/cof/krypandenej.mdl")
	util.PrecacheModel("models/vj_cofr/cof/children.mdl")	
	util.PrecacheModel("models/vj_cofr/cof/faceless.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faceless2.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faceless3.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faceless_twister.mdl")
	util.PrecacheModel("models/vj_cofr/cof/faceless_twisterv.mdl")
    util.PrecacheModel("models/vj_cofr/cof/upper.mdl")
    util.PrecacheModel("models/vj_cofr/cof/suicider.mdl")
    util.PrecacheModel("models/vj_cofr/cof/psycho.mdl")
    util.PrecacheModel("models/vj_cofr/cof/taller.mdl")
    util.PrecacheModel("models/vj_cofr/cof/stranger.mdl")
    util.PrecacheModel("models/vj_cofr/cof/spitter.mdl")
    util.PrecacheModel("models/vj_cofr/cof/hanger.mdl")
    util.PrecacheModel("models/vj_cofr/cof/hangman.mdl")
    util.PrecacheModel("models/vj_cofr/cof/flygare.mdl")
    util.PrecacheModel("models/vj_cofr/cof/dreamer.mdl")	
    util.PrecacheModel("models/vj_cofr/cof/dreamerrunner.mdl")
    util.PrecacheModel("models/vj_cofr/cof/crazyrumpel.mdl")	
    util.PrecacheModel("models/vj_cofr/cof/sawer.mdl")
    util.PrecacheModel("models/vj_cofr/cof/sawrunner.mdl")
    util.PrecacheModel("models/vj_cofr/cof/mace.mdl")
    util.PrecacheModel("models/vj_cofr/cof/sawcrazy.mdl")
    util.PrecacheModel("models/vj_cofr/cof/carcass.mdl")
    util.PrecacheModel("models/vj_cofr/cof/craig.mdl")
    util.PrecacheModel("models/vj_cofr/cof/booksimon.mdl")
    util.PrecacheModel("models/vj_cofr/cof/booksimon_m.mdl")
    util.PrecacheModel("models/vj_cofr/cof/doctor.mdl")
    util.PrecacheModel("models/vj_cofr/cof/sicksimon_sui.mdl")	
    util.PrecacheModel("models/vj_cofr/cof/sicksimon.mdl")	
    util.PrecacheModel("models/vj_cofr/aom/bullsquid.mdl")
    util.PrecacheModel("models/vj_cofr/aom/headcrab.mdl")
    util.PrecacheModel("models/vj_cofr/aom/controller.mdl")
    util.PrecacheModel("models/vj_cofr/aom/agrunt.mdl")
    util.PrecacheModel("models/vj_cofr/aom/mouth_monster.mdl")
    util.PrecacheModel("models/vj_cofr/aom/david_monster.mdl") 
    util.PrecacheModel("models/vj_cofr/aom/wheelchair_monster.mdl") 	
	util.PrecacheModel("models/vj_cofr/aom/zombie.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie2.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie3.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie4.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie5.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie2_1.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie2_2.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie2_3.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie2_4.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie2_5.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie3_1.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie3_2.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie3_3.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie3_4.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie3_5.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie4_1.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie4_2.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie4_3.mdl")	
	util.PrecacheModel("models/vj_cofr/aom/zombie4_4.mdl")
	util.PrecacheModel("models/vj_cofr/aom/zombie4_5.mdl")
    util.PrecacheModel("models/vj_cofr/custom/slower1.mdl")
    util.PrecacheModel("models/vj_cofr/custom/slower3.mdl")
    util.PrecacheModel("models/vj_cofr/custom/slowerno.mdl") 
    util.PrecacheModel("models/vj_cofr/custom/slower10.mdl")  	
    util.PrecacheModel("models/vj_cofr/custom/croucher.mdl")
    util.PrecacheModel("models/vj_cofr/custom/crawler.mdl")
    util.PrecacheModel("models/vj_cofr/custom/crawler2.mdl")
    util.PrecacheModel("models/vj_cofr/custom/krypandenej.mdl")
    util.PrecacheModel("models/vj_cofr/custom/faceless_claw.mdl")
    util.PrecacheModel("models/vj_cofr/custom/faster_clown.mdl")
    util.PrecacheModel("models/vj_cofr/custom/duorunner.mdl")
    util.PrecacheModel("models/vj_cofr/custom/psychopumpkin.mdl") 	
	
-- !!!!!! DON'T TOUCH ANYTHING BELOW THIS !!!!!! -------------------------------------------------------------------------------------------------------------------------
	AddCSLuaFile(AutorunFile)
	VJ.AddAddonProperty(AddonName,AddonType)
else
	if (CLIENT) then
		chat.AddText(Color(0,200,200),PublicAddonName,
		Color(0,255,0)," was unable to install, you are missing ",
		Color(255,100,0),"VJ Base!")
	end
	timer.Simple(1,function()
		if not VJF then
			if (CLIENT) then
				VJF = vgui.Create("DFrame")
				VJF:SetTitle("ERROR!")
				VJF:SetSize(790,560)
				VJF:SetPos((ScrW()-VJF:GetWide())/2,(ScrH()-VJF:GetTall())/2)
				VJF:MakePopup()
				VJF.Paint = function()
					draw.RoundedBox(8,0,0,VJF:GetWide(),VJF:GetTall(),Color(200,0,0,150))
				end
				
				local VJURL = vgui.Create("DHTML",VJF)
				VJURL:SetPos(VJF:GetWide()*0.005, VJF:GetTall()*0.03)
				VJURL:Dock(FILL)
				VJURL:SetAllowLua(true)
				VJURL:OpenURL("https://sites.google.com/site/vrejgaming/vjbasemissing")
			elseif (SERVER) then
				timer.Create("VJBASEMissing",5,0,function() print("VJ Base is Missing! Download it from the workshop!") end)
			end
		end
	end)
end